kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: bank-hpa
  namespace: bank
spec:
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: bankingappui-deployment

  minReplicas: 1
  maxReplicas: 5

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 2
